# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './src/gui/AddEdit_MAV.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Add_mav_Dialog(object):
    def setupUi(self, Add_mav_Dialog):
        Add_mav_Dialog.setObjectName("Add_mav_Dialog")
        Add_mav_Dialog.resize(400, 171)
        self.Add_mav_buttonBox = QtWidgets.QDialogButtonBox(Add_mav_Dialog)
        self.Add_mav_buttonBox.setGeometry(QtCore.QRect(110, 140, 166, 24))
        self.Add_mav_buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.Add_mav_buttonBox.setObjectName("Add_mav_buttonBox")
        self.layoutWidget = QtWidgets.QWidget(Add_mav_Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 371, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.Add_mav_gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.Add_mav_gridLayout.setContentsMargins(0, 0, 0, 0)
        self.Add_mav_gridLayout.setObjectName("Add_mav_gridLayout")
        self.jit_id_label = QtWidgets.QLabel(self.layoutWidget)
        self.jit_id_label.setObjectName("jit_id_label")
        self.Add_mav_gridLayout.addWidget(self.jit_id_label, 0, 0, 1, 1)
        self.jit_id_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.jit_id_lineEdit.setObjectName("jit_id_lineEdit")
        self.Add_mav_gridLayout.addWidget(self.jit_id_lineEdit, 0, 1, 1, 1)

        self.retranslateUi(Add_mav_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Add_mav_Dialog)

    def retranslateUi(self, Add_mav_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Add_mav_Dialog.setWindowTitle(_translate("Add_mav_Dialog", "Dialog"))
        self.jit_id_label.setText(_translate("Add_mav_Dialog", "JIT ID :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Add_mav_Dialog = QtWidgets.QDialog()
    ui = Ui_Add_mav_Dialog()
    ui.setupUi(Add_mav_Dialog)
    Add_mav_Dialog.show()
    sys.exit(app.exec_())
