# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './src/gui/AuctionLog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Auction_log_Dialog(object):
    def setupUi(self, Auction_log_Dialog):
        Auction_log_Dialog.setObjectName("Auction_log_Dialog")
        Auction_log_Dialog.resize(596, 771)
        self.auction_log_textBrowser = QtWidgets.QTextBrowser(Auction_log_Dialog)
        self.auction_log_textBrowser.setGeometry(QtCore.QRect(20, 70, 561, 621))
        self.auction_log_textBrowser.setObjectName("auction_log_textBrowser")
        self.auction_log_buttonBox = QtWidgets.QDialogButtonBox(Auction_log_Dialog)
        self.auction_log_buttonBox.setGeometry(QtCore.QRect(400, 720, 171, 24))
        self.auction_log_buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel)
        self.auction_log_buttonBox.setObjectName("auction_log_buttonBox")
        self.auction_log_label = QtWidgets.QLabel(Auction_log_Dialog)
        self.auction_log_label.setGeometry(QtCore.QRect(30, 30, 81, 16))
        self.auction_log_label.setObjectName("auction_log_label")
        self.auction_log_line = QtWidgets.QFrame(Auction_log_Dialog)
        self.auction_log_line.setGeometry(QtCore.QRect(20, 50, 551, 16))
        self.auction_log_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.auction_log_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.auction_log_line.setObjectName("auction_log_line")

        self.retranslateUi(Auction_log_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Auction_log_Dialog)

    def retranslateUi(self, Auction_log_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Auction_log_Dialog.setWindowTitle(_translate("Auction_log_Dialog", "Dialog"))
        self.auction_log_textBrowser.setHtml(_translate("Auction_log_Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.auction_log_label.setText(_translate("Auction_log_Dialog", "Auction logs :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Auction_log_Dialog = QtWidgets.QDialog()
    ui = Ui_Auction_log_Dialog()
    ui.setupUi(Auction_log_Dialog)
    Auction_log_Dialog.show()
    sys.exit(app.exec_())
